name: Release tarball
on: 
  push:
    tags:
    - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: topsecret
          MYSQL_DATABASE: dbix_mariadb_test
          MYSQL_ROOT_PASSWORD: topsecret
    steps:
    - uses: actions/checkout@v3
    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
    - name: installdeps
      run: cpanm --notest --installdeps .
    - name: build
      run: perl Makefile.PL && make && make manifest
    - run: make disttest
      env:
          DBICTEST_MARIADB_DSN: "dbi:MariaDB:database=dbix_mariadb_test;host=127.0.0.1;port=${{ job.services.mariadb.ports[3306] }}"
          DBICTEST_MARIADB_USER: "user"
          DBICTEST_MARIADB_PASS: "topsecret"
          RELEASE_TESTING: 1
    - run: make dist
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "DBIx-Class-Storage-DBI-MariaDB-*.tar.gz"